version: '3.4'
services:
  db:
    image: catapandanilo/mysql-compasso-crud
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: compasso_crud
    ports:
      - "3308:3306"
    networks:
      - network
  compasso-crud:
    image: catapandanilo/compasso-crud
    restart: always
    build: ./compassoCrud
    working_dir: /compassoCrud
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./compassoCrud:/compassoCrud
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - network
networks:
    network:
        driver: bridge